//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFIrst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NettrainingEntities1 : DbContext
    {
        public NettrainingEntities1()
            : base("name=NettrainingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deaprtment> Deaprtments { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
    
        public virtual ObjectResult<USP_GETEMPLOYEENAME_Result> USP_GETEMPLOYEENAME(string eMP_NAME)
        {
            var eMP_NAMEParameter = eMP_NAME != null ?
                new ObjectParameter("EMP_NAME", eMP_NAME) :
                new ObjectParameter("EMP_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GETEMPLOYEENAME_Result>("USP_GETEMPLOYEENAME", eMP_NAMEParameter);
        }
    }
}
