// <auto-generated />
namespace PolarisWeb1.Demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Created_DeptEmp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Created_DeptEmp));
        
        string IMigrationMetadata.Id
        {
            get { return "202409181105596_Created_DeptEmp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
